### ISSUE TITLE
Feature: disable removal of an invite before it's revoked

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/devops-credential-issuer#20]
### Background:
For now, admin users on the issuer app can delete an invitation directly, which removes the whole record. This makes it impossible to revoke the credential afterwards.

### Expected behaviour:
Disable the delete/remove button for invitations if it's issued but not revoked. OR just disable that totally?

**Comment by esune** [comment]
A new build with fixes for this has been started. Now, once a credential is issued IF it is revocable it will not be possible to delete the invite.
