### ISSUE TITLE
Help needed: diagram or documentation to explain the structure of all relavent components

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/devops-credential-issuer#21]
### Background:
There are several components currently living in one namespace for VC to integrate with KeyCloak. This is quite confusing for someone to pick it up themselves.

### Expected:
Documents and some diagram to explain how each component work together. And anything else that's important to know.

**Comment by esune** [comment]
@ShellyXueHan are you looking for documentation "just" on the VC integration part, or also on the issuer app as well?

There are some docs for [vc-authn-oidc](https://github.com/bcgov/vc-authn-oidc/tree/master/docs) that may be too complicated for what we need, in which case I can generate a "skimmed" version of the docs for our use-case.

**Comment by esune** [comment]
Project is now inactive, closing open issues.
